### ISSUE TITLE
更换字体来源，字体下载出错

### ISSUE THREAD

**Issue by Pengustc** [XiangyunHuang/notesdown#65]
运行结果：
试开URL’http://simonsoftware.se/other/xkcd.ttf'
Quitting from lines 2-126 (index.Rmd) 
Error in download.file("http://simonsoftware.se/other/xkcd.ttf", dest = path.expand("~/.fonts/xkcd.ttf"),  : 
  无法打开URL'http://simonsoftware.se/other/xkcd.ttf'
Calls: local ... withCallingHandlers -> withVisible -> eval -> eval -> download.file

停止执行
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile index.Rmd
Calls: <Anonymous> ... render_new_session -> tryCatch -> tryCatchList -> Rscript_render
停止执行

**Comment by XiangyunHuang** [comment]
@Pengustc 你单独打开 <http://simonsoftware.se/other/xkcd.ttf> 试试，可以下载啊

请贴出你的 `sessionInfo()`
