### ISSUE TITLE
Feature Request: add badge?

### ISSUE THREAD

**Issue by JiaxiangBU** [XiangyunHuang/notesdown#74]
For package and project developers, it is good to add badges to show the status of a project and package, like some usethis package function.
I would like to collaborate this part.

**Comment by XiangyunHuang** [comment]
@JiaxiangBU 
1. 已添加了 badge， 这个项目是一些临时的笔记，当初基本没考虑内容分类和项目管理，现在来看比较头大，其实更适合放在博客里面。
1. 我已经把你列为合作者，欢迎来贡献

**Comment by JiaxiangBU** [comment]
@XiangyunHuang 好的，那我先按照 bookdown 先完成 badge 部分，之后的展现方式（如 Gitbook 还是博客），看看你想有更好的方式。

初稿弄完后，会通知你。
