### ISSUE TITLE
Bug Report: build book 的时间过长的问题

### ISSUE THREAD

**Issue by JiaxiangBU** [XiangyunHuang/notesdown#76]
@XiangyunHuang 
我今天尝试 build book 的时候，发现其实需要的时间比较长。
随着这个书的内容增加，如果新增内容，进行 build book 的话，每次时间会过长。
这里会考虑有什么其他更好的方式么？我目前的想法是

1. 我不太熟悉 bookdown，不知道能不能分章节完成 rmarkdown 底层的 knit，这样如果是更新某一章节，只build对应的章节，这样时间应该会少很多。
1. 我想了下，按照之前的讨论，换成博客的框架，如 blogdown 可能会好一些？
但是这个基本上会改变整体的框架，可能需要另一个 branch 来开发了，想看看你的想法。

![image](https://user-images.githubusercontent.com/15884785/55678900-14952180-5934-11e9-8e9e-3767f6411e75.png)

**Comment by XiangyunHuang** [comment]
@JiaxiangBU 

1.  这里 bookdown 是分章节 knitr 的，就是 K-M 方式，内容越多，在 Travis-CI 上 构建时间越长，这是不可避免的，但是我对 R 包和编译中间文件缓存，构建时间会大大减少的，只是第一次构建会花费比较多的时间。解决办法是要么放弃 Travis-CI 测试，把构建的结果本地上传至 gh-pages 分支

2.  我想首先捋一捋结构，内容上按章节归类。换 blogdown 也可以，最重要是有一个比较详细的大纲，作为分门别类的依据
